# Generated by Django 2.1.7 on 2019-06-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190615_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Bug')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={},
        ),
    ]
